# Generated by Django 2.0.4 on 2018-04-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuId', models.CharField(max_length=9)),
                ('gitAddr', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('reason', models.TextField()),
            ],
        ),
    ]
