# Generated by Django 2.0.4 on 2018-04-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testTool', '0002_students_matchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
