# Generated by Django 2.0.4 on 2018-04-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testTool', '0003_auto_20180420_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
